[package]
name = "libsubs"
version = "0.1.0"
authors = ["Luc Tielen <luc.tielen@gmail.com>"]
build = "build.rs"

[dependencies]
libc = "0.2"

[dependencies.rustlibxml]
git = "https://github.com/Primordus/rust-libxml.git"
branch = "parse_xml_string"

[build-dependencies]
gcc = "0.3.20"
